name: CI Pipeline with Branch Logic

on:
  push:
    branches:
      - dev
      - main

jobs:
  build-and-test:
  
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up Python
        uses: actions/setup-python@42375524e23c212d93fbcf74499af319ef34b356 # v5.3.0
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest test_app.py

      - name: Log in to Docker Hub
        uses: docker/login-action@9780b0c442fcf1117581c676fc683adf49d4433b # v3.3.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine Docker tag prefix
        id: meta
        run: |
          if [ "${{ github.ref_name }}" == "main" ]; then
            echo "tag_prefix=prod" >> $GITHUB_OUTPUT
          else
            echo "tag_prefix=dev" >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        uses: docker/build-push-action@ca877d9245402d1537745e0e356e847c43706651 # v6.9.0
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/github-actions-ci:${{ steps.meta.outputs.tag_prefix }}-${{ github.sha }}